# Generated by Django 6.0.3 on 2026-03-15 04:33

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=48)),
                ('type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit'), ('investment', 'Investment')], max_length=16)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('income', 'Income'), ('outcome', 'Outcome')], max_length=8)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('education', 'Education'), ('pet', 'Pet'), ('self_care', 'Self Care'), ('home', 'Home'), ('debt', 'Debt'), ('loan', 'Loan'), ('work', 'Work'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('payment_planned_for', models.DateTimeField(blank=True, null=True)),
                ('ignored', models.BooleanField(default=False)),
                ('is_installment', models.BooleanField(default=False)),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='fate.account')),
                ('previous_installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_installment', to='fate.transaction')),
            ],
            options={
                'ordering': ('-due_at',),
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['account'], name='fate_transa_account_b4853a_btree'), django.contrib.postgres.indexes.BTreeIndex(fields=['direction'], name='fate_transa_directi_be2e9d_btree'), django.contrib.postgres.indexes.BTreeIndex(fields=['category'], name='fate_transa_categor_597db1_btree'), django.contrib.postgres.indexes.BTreeIndex(condition=models.Q(('paid_at__isnull', True)), fields=['paid_at'], name='unpaid_paid_at_idx')],
            },
        ),
    ]
